/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "fifo.v:1.1-47.10" *)
module synchronous_fifo(clk, rst_n, w_en, r_en, data_in, data_out, full, empty);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  (* src = "fifo.v:11.27-11.32" *)
  wire _11_;
  (* src = "fifo.v:11.27-11.32" *)
  wire _12_;
  (* src = "fifo.v:11.27-11.32" *)
  wire _13_;
  (* src = "fifo.v:6.16-6.21" *)
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  (* src = "fifo.v:3.15-3.19" *)
  wire _26_;
  (* src = "fifo.v:2.14-2.19" *)
  wire _27_;
  (* src = "fifo.v:3.9-3.13" *)
  wire _28_;
  (* force_downto = 32'd1 *)
  (* src = "fifo.v:24.25-24.37|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  (* unused_bits = "1 2" *)
  wire [2:0] _29_;
  (* force_downto = 32'd1 *)
  (* src = "fifo.v:24.25-24.37|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [2:0] _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  (* src = "fifo.v:2.9-2.12" *)
  input clk;
  wire clk;
  (* src = "fifo.v:11.27-11.32" *)
  wire [2:0] count;
  (* src = "fifo.v:4.23-4.30" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "fifo.v:5.28-5.36" *)
  output [7:0] data_out;
  wire [7:0] data_out;
  (* src = "fifo.v:6.16-6.21" *)
  output empty;
  wire empty;
  (* src = "fifo.v:6.10-6.14" *)
  output full;
  wire full;
  (* src = "fifo.v:3.15-3.19" *)
  input r_en;
  wire r_en;
  (* src = "fifo.v:9.34-9.39" *)
  wire [2:0] r_ptr;
  (* src = "fifo.v:2.14-2.19" *)
  input rst_n;
  wire rst_n;
  (* src = "fifo.v:3.9-3.13" *)
  input w_en;
  wire w_en;
  (* src = "fifo.v:9.27-9.32" *)
  wire [2:0] w_ptr;
  sky130_fd_sc_hd__nor3_1 _37_ (
    .A(_13_),
    .B(_12_),
    .C(_11_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nand2b_1 _38_ (
    .A_N(_26_),
    .B(_28_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__xnor2_1 _39_ (
    .A(_28_),
    .B(_26_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__xor2_1 _40_ (
    .A(_28_),
    .B(_26_),
    .X(_17_)
  );
  sky130_fd_sc_hd__xnor2_1 _41_ (
    .A(_11_),
    .B(_16_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__and2_0 _42_ (
    .A(_27_),
    .B(_18_),
    .X(_08_)
  );
  sky130_fd_sc_hd__xnor3_1 _43_ (
    .A(_12_),
    .B(_11_),
    .C(_15_),
    .X(_19_)
  );
  sky130_fd_sc_hd__o21ai_0 _44_ (
    .A1(_12_),
    .A2(_17_),
    .B1(_27_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__a21oi_1 _45_ (
    .A1(_17_),
    .A2(_19_),
    .B1(_20_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__maj3_1 _46_ (
    .A(_12_),
    .B(_11_),
    .C(_15_),
    .X(_21_)
  );
  sky130_fd_sc_hd__xnor2_1 _47_ (
    .A(_13_),
    .B(_15_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__xnor2_1 _48_ (
    .A(_21_),
    .B(_22_),
    .Y(_23_)
  );
  sky130_fd_sc_hd__nand2_1 _49_ (
    .A(_17_),
    .B(_23_),
    .Y(_24_)
  );
  sky130_fd_sc_hd__nand2_1 _50_ (
    .A(_13_),
    .B(_16_),
    .Y(_25_)
  );
  sky130_fd_sc_hd__a21boi_0 _51_ (
    .A1(_24_),
    .A2(_25_),
    .B1_N(_27_),
    .Y(_10_)
  );
  (* src = "fifo.v:14.3-27.6" *)
  sky130_fd_sc_hd__dfxtp_1 _52_ (
    .CLK(clk),
    .D(_32_),
    .Q(count[0])
  );
  (* src = "fifo.v:14.3-27.6" *)
  sky130_fd_sc_hd__dfxtp_1 _53_ (
    .CLK(clk),
    .D(_34_),
    .Q(count[1])
  );
  (* src = "fifo.v:14.3-27.6" *)
  sky130_fd_sc_hd__dfxtp_1 _54_ (
    .CLK(clk),
    .D(_36_),
    .Q(count[2])
  );
  assign _30_[0] = _29_[0];
  assign data_out = 8'h00;
  assign full = 1'h0;
  assign r_ptr = 3'h0;
  assign w_ptr = 3'h0;
  assign _13_ = count[2];
  assign _12_ = count[1];
  assign _11_ = count[0];
  assign _28_ = w_en;
  assign _26_ = r_en;
  assign empty = _14_;
  assign _27_ = rst_n;
  assign _32_ = _08_;
  assign _34_ = _09_;
  assign _36_ = _10_;
endmodule
